ProfileGrabber/profileGrabber/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('discover.html', views.discover, name='discover'),
    url('collection.html', views.collection, name='collection'),

]

ProfileGrabber/profiler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^profileGrabber/', include('profileGrabber.urls')),
    url(r'^admin/', admin.site.urls),
]

ProfileGrabber/profileGrabber/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class SavedUser(models.Model):
    source = models.CharField(max_length=16)
    handle = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    influencer = models.CharField(max_length=16)
    followers = models.IntegerField()
    following = models.IntegerField()
    description = models.TextField()
    def __str__(self):
        return self.handle

class Tweets(models.Model):
    user_name = models.ForeignKey(SavedUser)
    tweet_text = models.CharField(max_length=140)
    def __str__(self):
        return self.tweet_text
    

ProfileGrabber/profileGrabber/forms.py
from django import forms

class HandleForm(forms.Form):
	twitter_handle = forms.CharField(label='Twitter Handle', max_length=100)

class PushForm(forms.Form):
	push_source = forms.CharField(label='Source', max_length=16)
	push_handle = forms.CharField(label='Handle', max_length=100)

ProfileGrabber/profileGrabber/views.py
from django.shortcuts import render, get_object_or_404
from .models import SavedUser, Tweets
from . import tweet_profiler
from .forms import HandleForm, PushForm


def index(request):
    context = {}
    return render(request, 'profileGrabber/index.html', context)


def discover(request):
    profile = tweet_profiler.get_profile ("realDonaldTrump")
    influencer = "NO"

    if request.method == 'POST':
        render_handle = HandleForm(request.POST)
        render_push = PushForm(request.POST)

        if render_handle.is_valid():
            profile = tweet_profiler.get_profile(render_handle.cleaned_data['twitter_handle'])
            render_push = PushForm()

        elif render_push.is_valid():
            profile = tweet_profiler.get_profile(render_push.cleaned_data['push_handle'])
            tweets = tweet_profiler.get_tweets(render_push.cleaned_data['push_handle'])

            try:
                s = SavedUser(
                    source = render_push.cleaned_data['push_source'],
                    handle = profile.screen_name,
                    name = profile.name,
                    followers = profile.followers_count,
                    following = profile.friends_count,
                    influencer = influencer,
                    description = profile.description
                    )
                s.save()

                for tweet in tweets:
                    t = Tweets(
                        user_name = s, 
                        tweet_text = tweet.text
                        )
                    t.save()
            
            except:
                s = ""
                render_handle = HandleForm() 

        else:
            render_handle = HandleForm()
            render_push = PushForm()
    
    if profile.followers_count > 500:
        influencer = "YES"

    context = {
    'profile': profile,
    'influencer': influencer,
    }
    return render(request, 'profileGrabber/discover.html', context)


def collection(request):
    saved_users = SavedUser.objects.all()
    tweets = Tweets.objects.all()
    context = {
    'saved_users': saved_users,
    'tweets': tweets,
    }
    return render(request, 'profileGrabber/collection.html', context)

ProfileGrabber/profileGrabber/templates/profileGrabber/collection.html
<!-- Week2 Challenge: Build the Collections View
It seems that this page is completely missing, and we're not sure what to
do about it. If you're looking for a challenge, fix this page and make it
nice. Remember that the purpose of the page is to render a collection of
Twitter profiles that were saved in a database. If you want to learn more,
remember you can visit femto.cs.dal.ca/profileGrabber any time.-->
{% extends "profileGrabber/template.html" %}

{% block content %}


    <div class="container" style="margin-top:40px;">
  <ul class="collapsible" data-collapsible="accordion">
  {% for user in saved_users %}
      <li>
        <div class="collapsible-header"><i class="material-icons">filter_drama</i>{{ user.handle }}</div>

        {% for tweet in user.tweets_set.all %}

        <div class="collapsible-body"><p>{{ tweet.tweet_text }}</p></div>

        {% endfor %}
      </li>
  {% endfor %}


    </div>     
      
    </div>
    <!-- Materialize has a special footer tag that renders a nice-looking footer.
    This looks fine for now. When we bring these into Django we should keep this
    one template that is used by all the pages, rather than rewriting it each time.-->


{% endblock %}

ProfileGrabber/profileGrabber/templates/profileGrabber/discover.html
{% extends "profileGrabber/template.html" %}

{% block content %}

{% if profile %}
<h3>Discover users to add to your list</h3>
<div class="row">
  <form action="" method="post">
    {% csrf_token %}
    <div class="input-field col m6">
      <label for="twitter_handle">Find a new profile (eg. "potus") </label>
      <input class = "col m6" id="twitter_handle" type="text" name="twitter_handle" maxlength="100" required value="{{ profile.screen_name }}">
      <button class="btn waves-effect red" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    </div>
  </form>
</div>

<div class="row">
  <div class="col m3">
    <h4>{{ profile.name }}</h4>
    <span style="font-weight:bold;">{{ profile.screen_name }}</span>
    <span>{{ profile.location }}</span>
  </div>
  <div class="col m3">
    <h4>Influencer: {{ influencer }}</h4>
    <!-- Modal Trigger -->
    <a class="waves-effect waves-light btn green" href="#modal1">What's this?</a>

    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4>Influencers</h4>
        <p>Influencers are people who start trends on Twitter. Typically these users have a large number of followers, and a large number of people actually read what they post. We can create any number of algorithms to determine influencers, but we kept it simple for this tutorial: people with over 500 followers.</p>
      </div>
      <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">OK</a>
      </div>
    </div>
  </div>
  <div class="col m3">
    <h4>Followers: {{ profile.followers_count }}</h4>
    <span style="font-weight:bold;">Following:</span>
    <span>{{ profile.friends_count }}</span>
  </div>
  <div class="col m3">
    <form action="" method="post">
      {% csrf_token %}
      <input type="hidden" name="push_source" value="Web">
      <input type="hidden" name="push_handle" value="{{ profile.screen_name }}">
      <button class="btn-floating btn-large waves-effect waves-light red" type="submit" name="action">
          <i class="material-icons">add</i>
      </button>
    </form>
  </div>
</div>
<div class="row">
  <div class="col m12">
    <blockquote>
      <p>{{ profile.description }}</p>
      <footer>{{ profile.screen_name }}<cite title="Source Title"> Profile Summary </cite></footer>
    </blockquote>
  </div>
</div>

{% else %}
    <p>Error!</p>
{% endif %}

{% endblock %}

ProfileGrabber/profileGrabber/templates/profileGrabber/index.html
{% extends "profileGrabber/template.html" %}

{% block content %}

{% load static %}

      
      <h3 style="margin-bottom: 50px;">Welcome to your latest procrastination fix.</h3>
      <div class="row">
        <div class="col m6">
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header active"><i class="material-icons">info_outline</i>Welcome to ProfileGrabber</div>
              <div class="collapsible-body"><p>ProfileGrabber is a WebApp built using Python Django. It makes use of html/css and shows us how data mining can be applied to social media.</p></div>
            </li>
            <li>
              <div class="collapsible-header"><i class="material-icons">whatshot</i>Expand Your Network</div>
              <div class="collapsible-body"><p>Now that you are here, feel free to check out ProfileGrabber's functionality. Find twitter users, understand their influence and add the to your own list to keep track of your activity. Hit the + icon in the Discover tab to add a user to your Collection.</p></div>
            </li>
            <li>
              <div class="collapsible-header"><i class="material-icons">grade</i>Go forth and waste time</div>
             
          </ul>
        </div>
        <div class="col m6">
          <img class="bird" style="width: 100%; display: block; margin-left: auto; margin-right: auto;" src="{% static 'dank.jpeg' %}">
        </div>
      </div>
      <div class="row">
        <div class="col m4" style="text-align: center;">
          <i class="large material-icons">perm_identity</i>
          <h5>Discover twitter profiles<h5>
        </div>
        <div class="col m4 icon-prievew" style="text-align: center;">
          <i class="large material-icons">group_work</i>
          <h5>Add profiles to a list<h5>
        </div>
        <div class="col m4" style="text-align: center;">
          <i class="large material-icons">done</i>
          <h5>Waste time like a Pro!</h5>
        </div>
      </div>
      </div>


   {% endblock %}

ProfileGrabber/profileGrabber/templates/profileGrabber/index1.html
{% extends "profileGrabber/template.html" %}
{% load static %}

{% block content %}

  <h1>Twitter Profiler</h1>
  <div class="row">
    <div class="col m6">
      <img style="display: block; margin-left: auto; margin-right: auto;" src="{%static 'twitter.svg' %}">
    </div>
    <div class="col m6">
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header active"><i class="material-icons">info_outline</i>Start with the basics</div>
          <div class="collapsible-body"><p>This tutorial assumes that you are familiar with object oriented programing. It also helps to know html/css, which you can learn online on your own.</p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="material-icons">whatshot</i>Code like crazy</div>
          <div class="collapsible-body"><p>Though we only meet for 90 minutes a week, it will take many people at least 10 hours each week (for five weeks) to become famililar enough with these skills to pull a project off.</p></div>
        </li>
        <li>
          <div class="collapsible-header"><i class="material-icons">grade</i>Master the Django stack</div>
          <div class="collapsible-body"><p>Whether this is your first stack or one of many, Django is a good stack to master for applications that work with data. Read more about pythons powerful data science libraries like NumPy, NLTK, SciPy, Pandas... </p></div>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col m4" style="text-align: center;">
      <i class="large material-icons">perm_identity</i>
      <h5>Discover twitter profiles<h5>
    </div>
    <div class="col m4 icon-prievew" style="text-align: center;">
      <i class="large material-icons">group_work</i>
      <h5>Add profiles to a list<h5>
    </div>
    <div class="col m4" style="text-align: center;">
      <i class="large material-icons">done</i>
      <h5>Learn the Django stack!</h5>
    </div>
  </div>

{% endblock %}

ProfileGrabber/profileGrabber/templates/profileGrabber/template.html
{% load static %}

<html>
  <head>
    <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css using the same CDN as index.html-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
      <link rel="stylesheet" type="text/css" href="assets/style.css"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <!-- The nav div is the navbar. Make sure this is right... seems like the
    links are broken and the color is wrong. You can find the broken links in the
    href="" for each li or the logo -->
    <nav class="purple darken-4">
      <div class="nav-wrapper container">
        <a href="/profileGrabber/" class="brand-logo">ProfileGrabber</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/profileGrabber">Home</a></li>
          <li><a href="discover.html">Discover</a></li>
          <li><a href="collection.html">Collection</a></li>
        </ul>
        <ul  class="side-nav" id="mobile-demo">
          <li><a href="/profileGrabber">Home</a></li>
          <li><a href="discover.html">Discover</a></li>
          <li><a href="collection.html">Collection</a></li>
        </ul>
      </div>
    </nav>
    <div class="container" style="margin-top:40px;">
      {% block content %} {% endblock %}
     </div>
     <footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Data Science just got social</h5>
                <p class="grey-text text-lighten-4">This is an Info 6850 Data Science Final Project hosted at Dalhousie University in Halifax, Nova Scotia,CA </p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="http://shiftkeylabs.ca/">Shiftkey Labs</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://github.com/cdconrad/shiftkey-py">Github</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            (c) 2017 Jenny Farbstein learns to Python
            <a class="grey-text text-lighten-4 right"> @FarbyPython</a>
            </div>
          </div>
        </footer>
    <!-- Ah, the REAL end of our HTML doc. This is a critical region... materialize
    will not work without JQuery. Here is where we must add the JQuery CDN in
    order for Materialize to render its cool features. Note how it is sandwiched
    between <script> tags. Try adding src = "https://code.jquery.com/jquery-2.1.1.min.js".
    Also, the materialize JS document is referenced in the footer here-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <!-- Currently our modal does not work. We need to add some custom javascript
    for this. check out http://materializecss.com/modals.html-->
    <script>
      $(document).ready(function(){
        $('.modal').modal();
        //We are missing two things. The code for the sideNav is written below.
        //We also need to add something for the modal.
        //$(".button-collapse").sideNav();
      });
    </script>
  </body>
</html

ProfileGrabber/profileGrabber/templates/profileGrabber/template1.html
{% load static %}

<html>
  <head>
    <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <nav class="blue">
      <div class="nav-wrapper container">
        <a href="/profileGrabber/" class="brand-logo">Twitter Profiler</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/profileGrabber">Home</a></li>
          <li><a href="discover.html">Discover</a></li>
          <li><a href="collection.html">Collection</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="/profileGrabber">Home</a></li>
          <li><a href="discover.html">Discover</a></li>
          <li><a href="collection.html">Collection</a></li>
        </ul>
      </div>
    </nav>
    <div class="container" style="margin-top:40px;">
      {% block content %} {% endblock %}
    </div>
    <footer class="page-footer blue">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Part of the Shiftkey-py Tutorial</h5>
                <p class="grey-text text-lighten-4">Shiftkey-py is a free tutorial run at Shiftkey Labs at Dalhousie University in Halifax, Canada. Visit the Github repo or Shiftkey site for more information. </p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="http://shiftkeylabs.ca/">Shiftkey Labs</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://github.com/cdconrad/shiftkey-py">Github</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Colin Conrad
            <a class="grey-text text-lighten-4 right" href="http://web.cs.dal.ca/~cconrad">Contact Me</a>
            </div>
          </div>
        </footer>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $('.modal').modal();
        $(".button-collapse").sideNav();
      });
    </script>
  </body>
</html>